In [1]:
#Load Library
import pandas as pd
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np

dataset = pd.read_excel("https://github.com/alfianpr/perhitungan-volume-objek-simetri/blob/main/telur/telur.xlsx?raw=true")\
            .drop(["no"], axis=1)

pixel = [] #membuat dataframe pixel

for num in range (1, 101): # Range citra 1 - 100
    num_img = str(num)
    path = r"C:\Users\acer\OneDrive - Universitas Diponegoro\Documents\Thesis\telur\{}.jpg".format(num_img)
    img = cv.imread(path, 0) #load citra

    # Otsu's thresholding setelah Gaussian filtering
    blur = cv.GaussianBlur(img,(5,5),0)
    ret3,th3 = cv.threshold(blur,0,255,cv.THRESH_BINARY+cv.THRESH_OTSU)

    #Open Morphology untuk menghilangkan noise
    kernel = np.ones((5,5),np.uint8)
    opening = cv.morphologyEx(th3, cv.MORPH_OPEN, kernel)

    #Jumlah pixel yang memiliki nilai 255
    num = np.sum(opening == 255)
    
    pixel.append(num) #Menyimpan hasil jumlah pixel putih ke Dataframe pixel

dataset["pixel"] = pd.Series(pixel)

In [2]:
dataset

    volume  jarak  pixel
0       60   30.7  57378
1       50   30.7  53078
2       60   30.7  60613
3       50   30.7  53295
4       40   30.7  44062
..     ...    ...    ...
95      45   29.7  52728
96      55   29.7  55748
97      50   29.7  53157
98      50   29.7  55333
99      50   29.7  54478

[100 rows x 3 columns]

In [3]:
#Mengonversi volume ke satuan m^3 dan jarak ke m
dataset["volume"] = dataset["volume"] * 0.000001
dataset["jarak"] = dataset["jarak"] * 0.01

dataset.to_excel("dataframe_telur.xlsx")