In [24]:
#Load Library
import pandas as pd
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np

dataset = pd.read_excel("https://github.com/alfianpr/perhitungan-volume-objek-simetri/raw/main/beras/beras.xlsx")\
            .drop(["pixel", "no"], axis=1)

pixel = [] #membuat dataframe pixel

for num in range (1, 101): # Range citra 1 - 100
    num_img = str(num)
    path = r"C:\Users\acer\OneDrive - Universitas Diponegoro\Documents\Thesis\beras\{}.jpg".format(num_img)
    img = cv.imread(path, 0) #load citra dari folder

    # Otsu's thresholding setelah Gaussian filtering
    blur = cv.GaussianBlur(img,(5,5),0)
    ret3,th3 = cv.threshold(blur,0,255,cv.THRESH_BINARY+cv.THRESH_OTSU)

    #Open Morphology untuk menghilangkan noise
    kernel = np.ones((5,5),np.uint8)
    opening = cv.morphologyEx(th3, cv.MORPH_OPEN, kernel)

    #Jumlah pixel yang memiliki nilai 255
    num = np.sum(opening == 255)
    
    pixel.append(num) #Menyimpan hasil jumlah pixel putih ke Dataframe pixel

dataset["pixel"] = pd.Series(pixel)

In [25]:
#Melihat dataframe
dataset

    volume  jarak   pixel
0       40   30.5  202394
1       20   30.5  131027
2       25   30.5  130709
3       50   30.5  233374
4       20   30.5  124836
..     ...    ...     ...
95      40   32.2  165869
96      30   32.2  135835
97      45   32.2  174188
98      40   32.2  167557
99      35   32.2  155597

[100 rows x 3 columns]

In [6]:
dataset.to_excel("dataframe_pixel.xlsx")